name: lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run pre-commit test
      run: |
        curl https://pre-commit.com/install-local.py | python -
        pre-commit run -a
